data_config:
  splits:
    train: 0.8
    valid: 0.1
    test: 0.1
  batch_size: 128
  mutag_x: true  

model_config:
  model_name: PNA
  hidden_size: 80
  n_layers: 4
  dropout_p: 0.3
  aggregators:
    - mean
    - min
    - max
    - std
    - sum
  scalers: false

shared_config:
  learn_edge_att: false


RayE_config:
  method_name: 'RayE'
  epochs: 50
  lr: 1.0e-3
  beta: 0.05
  weight_decay: 3.0e-6

  from_scratch: true
